import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { checkAccess, getDrafts, saveDraft } from '../../services/stamppad.service';
import { safeReplace } from '../../services/navigation';
import DocumentEditor from '../../components/stamp-pad/DocumentEditor';
import AppBottomNav from '../../components/navigation/AppBottomNav';
import { Colors } from '../../constants/colors';
import { FontFamily } from '../../constants/typography';

const TEMPLATE_LABELS = { standard: 'Standard Official', press: 'Press Release', internal: 'Internal Memo' };

export default function StampPadScreen() {
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [template, setTemplate] = useState('standard');
  const [stampEnabled, setStampEnabled] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);

  const { data: accessData, isLoading: accessLoading } = useQuery({ queryKey: ['stamp-pad-access'], queryFn: checkAccess });

  useEffect(() => {
    if (!accessLoading && accessData && !accessData.hasAccess) {
      safeReplace('/stamp-pad/access-restricted');
    }
  }, [accessData, accessLoading]);

  const { data: drafts = [], refetch: refetchDrafts } = useQuery({
    queryKey: ['stamp-pad-drafts'],
    queryFn: getDrafts,
    enabled: accessData?.hasAccess === true,
  });

  const handleGenerateLetter = async () => {
    if (!subject.trim()) { Alert.alert('Validation', 'Please enter a subject.'); return; }
    if (!body.trim()) { Alert.alert('Validation', 'Please enter the letter body.'); return; }
    setGenerating(true);
    try {
      const stampHtml = stampEnabled
        ? `<div style="border:3px solid #006E2E;border-radius:50%;width:80px;height:80px;display:flex;align-items:center;justify-content:center;margin:16px auto;text-align:center;font-weight:bold;color:#006E2E;font-size:11px;">RLP<br/>OFFICIAL</div>`
        : '';
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${subject}</title>
        <style>body{font-family:Arial,sans-serif;margin:40px;color:#1F1B10;}h2{font-size:18px;margin-bottom:8px;}
        .template-label{font-size:11px;color:#888;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:24px;}
        .body{font-size:14px;line-height:1.8;white-space:pre-wrap;}
        .footer{margin-top:40px;font-size:12px;color:#888;border-top:1px solid #eee;padding-top:12px;}</style></head>
        <body><div class="template-label">${TEMPLATE_LABELS[template]}</div><h2>${subject}</h2>
        <div class="body">${body}</div>${stampHtml}
        <div class="footer">Generated by RLP Digital Connect</div></body></html>`;
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Save Letter PDF' });
      else Alert.alert('PDF Generated', `Saved to: ${uri}`);
    } catch (_e) { Alert.alert('Error', 'Could not generate PDF. Please try again.'); }
    finally { setGenerating(false); }
  };

  const handleSaveDraft = async () => {
    if (!subject.trim() && !body.trim()) { Alert.alert('Empty Draft', 'Please add some content before saving.'); return; }
    setSaving(true);
    try { await saveDraft({ subject, body, template, stampEnabled }); await refetchDrafts(); Alert.alert('Saved', 'Draft saved successfully.'); }
    catch (_e) { Alert.alert('Error', 'Could not save draft. Please try again.'); }
    finally { setSaving(false); }
  };

  const loadDraft = (draft) => { setSubject(draft.subject); setBody(draft.body); setTemplate(draft.template); setStampEnabled(draft.stampEnabled); };

  if (accessLoading) {
    return (
      <SafeAreaView style={styles.safeArea} edges={['top']}>
        <View style={styles.loadingContainer}><ActivityIndicator size="large" color={Colors.rlpGreen} /></View>
        <AppBottomNav />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safeArea} edges={['top']}>
      <View style={styles.header}>
        <Pressable style={({ pressed }) => [styles.backBtn, pressed && { opacity: 0.6 }]} onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Go back">
          <Text style={styles.backIcon}>←</Text>
        </Pressable>
        <Text style={styles.headerTitle}>Stamp Pad</Text>
        <View style={{ width: 36 }} />
      </View>

      <DocumentEditor subject={subject} body={body} template={template} stampEnabled={stampEnabled} onSubjectChange={setSubject} onBodyChange={setBody} onTemplateChange={setTemplate} onStampToggle={setStampEnabled} />

      <View style={styles.actions}>
        <Pressable style={({ pressed }) => [styles.generateBtn, pressed && { opacity: 0.85 }]} onPress={handleGenerateLetter} disabled={generating} accessibilityRole="button" accessibilityLabel="Generate Letter">
          {generating ? <ActivityIndicator color={Colors.onSurface} size="small" /> : <Text style={styles.generateBtnText}>📄  Generate Letter</Text>}
        </Pressable>
        <Pressable style={({ pressed }) => [styles.saveDraftBtn, pressed && { opacity: 0.75 }]} onPress={handleSaveDraft} disabled={saving} accessibilityRole="button" accessibilityLabel="Save Draft">
          {saving ? <ActivityIndicator color={Colors.onSurfaceVariant} size="small" /> : <Text style={styles.saveDraftBtnText}>Save Draft</Text>}
        </Pressable>
      </View>

      {drafts.length > 0 && (
        <View style={styles.draftsSection}>
          <Text style={styles.draftsSectionTitle}>Saved Drafts</Text>
          <FlatList
            data={drafts}
            keyExtractor={(item) => item.id}
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={styles.draftsList}
            renderItem={({ item }) => (
              <Pressable style={({ pressed }) => [styles.draftCard, pressed && { opacity: 0.8 }]} onPress={() => loadDraft(item)} accessibilityRole="button">
                <Text style={styles.draftSubject} numberOfLines={1}>{item.subject || 'Untitled'}</Text>
                <Text style={styles.draftDate}>{new Date(item.updatedAt).toLocaleDateString('en-IN')}</Text>
              </Pressable>
            )}
          />
        </View>
      )}
      <AppBottomNav />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8F9FA' },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.outlineVariant, backgroundColor: Colors.white },
  backBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  backIcon: { fontSize: 22, color: Colors.onSurface },
  headerTitle: { flex: 1, fontFamily: FontFamily.semiBold, fontSize: 18, color: Colors.onSurface, marginLeft: 4 },
  actions: { padding: 16, gap: 10, borderTopWidth: 1, borderTopColor: Colors.outlineVariant, backgroundColor: Colors.white },
  generateBtn: { backgroundColor: Colors.rlpYellow, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  generateBtnText: { fontFamily: FontFamily.semiBold, fontSize: 16, color: Colors.onSurface },
  saveDraftBtn: { borderWidth: 1, borderColor: Colors.outlineVariant, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  saveDraftBtnText: { fontFamily: FontFamily.semiBold, fontSize: 15, color: Colors.onSurfaceVariant },
  draftsSection: { backgroundColor: Colors.white, borderTopWidth: 1, borderTopColor: Colors.outlineVariant, paddingTop: 12, paddingBottom: 8 },
  draftsSectionTitle: { fontFamily: FontFamily.semiBold, fontSize: 13, color: Colors.onSurfaceVariant, paddingHorizontal: 16, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 },
  draftsList: { paddingHorizontal: 16, gap: 10 },
  draftCard: { backgroundColor: Colors.surfaceContainerLow, borderRadius: 10, padding: 12, width: 160, borderWidth: 1, borderColor: Colors.outlineVariant },
  draftSubject: { fontFamily: FontFamily.semiBold, fontSize: 13, color: Colors.onSurface, marginBottom: 4 },
  draftDate: { fontFamily: FontFamily.regular, fontSize: 11, color: Colors.onSurfaceVariant },
});
